version: '3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel-network

  php:
    build:
      context: ./php
      dockerfile: dockerfile
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - postgres
    networks:
      - laravel-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: root
      POSTGRES_DB: mydb
    networks:
      - laravel-network

networks:
  laravel-network: