# Use a imagem oficial do Nginx
FROM nginx:latest

# Copie o arquivo de configuração personalizado
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Exponha a porta 80
EXPOSE 80

# Mantenha o contêiner em execução
CMD ["nginx", "-g", "daemon off;"]